### ISSUE TITLE
Packet sc_p_cts

### ISSUE THREAD

**Issue by Nory23** [JOAOMASTER/Parse-of-opennos#3]
First off all, thanks for your parse, and second in my console shows this. Can you fix this please? Or tellme how fix this. Thanks

http://i66.tinypic.com/2ryoiz7.png

**Comment by RiverCZE** [comment]
no handler for this packet

**Comment by JOAOMASTER** [comment]
IF I THINK THAT THESE PACKAGES ARE NOT OR ARE NOT IMPLEMITTED BUT IF THEY ARE IN THE PACKET
